Repository Dintero/Dintero.Checkout.Web.SDK, pull requests merged in 2023-10, with the labels that each got.

#210 feat: add pop out mode
  README.md
  src/checkout.ts
  src/index.ts
  src/popOut.ts
  src/popOutBackdrop.ts
  src/popOutButton.ts
  src/subscribe.ts
  src/url.ts
  test/dintero-checkout-web-sdk.test.ts
Labels: checkout-sdk

#254 Replace depricated karma with vitest
  .github/workflows/build.yml
  .github/workflows/release.yml
  karma.conf.js
  package.json
  patches/vitest+0.34.6.patch
  test/dintero-checkout-web-sdk.test.ts
  yarn.lock
Labels: dependencies

#255 Use prettier to lint all files
  .github/workflows/build.yml
  .github/workflows/release.yml
  .prettierrc.yml
  .releaserc.json
  CHANGELOG.md
  README.md
  package.json
  src/checkout.ts
  src/createIframeAsync.ts
  src/index.ts
  src/popOut.ts
  src/popOutBackdrop.ts
  src/popOutButton.ts
  src/subscribe.ts
  src/url.ts
Labels: chore

#258 fix: pop out loaded check different origin
  src/popOut.ts
  src/url.ts
Labels: bug

#260 fix(package): install fails because of `postinstall` script
  package.json
Labels: bug
