Repository Dintero/Dintero.Checkout.Web.SDK, pull requests merged in 2024-12, with the labels that each got.

#429 fix(iframe):Adds cross origin clipboard-write for iframe
  src/createIframeAsync.ts
Labels: bug

#430 chore(deps-dev): bump webdriverio from 9.2.1 to 9.4.1
  .gitignore
  package.json
  yarn.lock
Labels: dependencies

#431 chore(vitest): Enable browser config option
  .vitest.config.mts
  package.json
Labels: chore
