Repository Dintero/Dintero.Checkout.Web.SDK, pull requests merged in 2024-02, with the labels that each got.

#322 fix(build): include ts declarations in release
  LICENSE
  package.json
Labels: bug, checkout-sdk

#326 feat(embed): add property "ui" to embed options
  src/index.ts
Labels: enhancement

#330 fix(build): add asset to github release
  .releaserc.json
Labels: checkout-sdk

#337 feat(embed): Allow hiding test message on creating iframe
  src/index.ts
  src/url.ts
  yarn.lock
Labels: enhancement
